/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 28 21:29:31 GMT 2017
 */

package brain.ga;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import brain.ga.Evaluator;
import brain.ga.Genome;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Genome_ESTest extends Genome_ESTest_scaffolding {

  //Test case number: 0
  /*
   * 2 covered goals:
   * Goal 1. Branch brain.ga.Genome.<init>()V: root-Branch in context: brain.ga.Genome:<init>()V
   * Goal 2. Branch brain.ga.Genome.getScore()D: I4 Branch 1 IFNE L23 - false in context: brain.ga.Genome:getScore()D
   */

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Genome genome0 = new Genome();
      // Undeclared exception!
      try { 
        genome0.getScore();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("brain.ga.Genome", e);
      }
  }

  //Test case number: 1
  /*
   * 2 covered goals:
   * Goal 1. Branch brain.ga.Genome.<init>()V: root-Branch in context: brain.ga.Genome:<init>()V
   * Goal 2. Branch brain.ga.Genome.initialize()V: root-Branch in context: brain.ga.Genome:initialize()V
   */

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Genome genome0 = new Genome();
      genome0.initialize();
  }

  //Test case number: 2
  /*
   * 2 covered goals:
   * Goal 1. Branch brain.ga.Genome.<init>()V: root-Branch in context: brain.ga.Genome:<init>()V
   * Goal 2. Branch brain.ga.Genome.getEvaluator()Lbrain/ga/Evaluator;: root-Branch in context: brain.ga.Genome:getEvaluator()Lbrain/ga/Evaluator;
   */

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Genome genome0 = new Genome();
      Evaluator evaluator0 = genome0.getEvaluator();
      assertNull(evaluator0);
  }
}
